set(BUILDNAME "IGSTK-VT-JUnit")
set(CTEST_PROJECT_NAME "IGSTK-VT")
set(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "lead2.poly.asu.edu")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=IGSTK-VT")
set(CTEST_DROP_SITE_CDASH TRUE)
