#created on: Feb 18, 2008
package org.igstk.validation.simulator

#list any import classes here.

import org.igstk.validation.simulator.IgstkvtStateMachineExecutor;
import org.igstk.validation.IgstkvtStateMachine;

#declare any global variables here


rule "Rule 1"
	
	when
		stateMachine : IgstkvtStateMachineExecutor(currentState  == "5DOFTrackerToolChannelNumberSpecifiedState" ,stateMachineId == "1") 
	then 
		System.out.println("Id of the stateMachine is *********TESTING******: "  + stateMachine.getStateMachineId());
		stateMachine.notifyListeners("DROOLS: The StateMachine " + stateMachine.getStateMachineName() + "  is in state " + " " + stateMachine.getCurrentState()+
					" which is against rules!!!" );
end

